# Generated by Django 3.0.3 on 2020-02-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20200213_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата закрытия:'),
        ),
        migrations.AddField(
            model_name='article',
            name='numb',
            field=models.FloatField(null=True, verbose_name='Номер лота'),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='article',
            name='statzakup',
            field=models.CharField(choices=[('draft', 'Ценовое предложение'), ('win', 'Открытый конкурс (на понижение)'), ('sended', 'Аукцион')], default='draft', max_length=10, verbose_name='Способ закупки'),
        ),
        migrations.AddField(
            model_name='article',
            name='yst',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=255, verbose_name='Заказчик:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование лота'),
        ),
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lots.Cities', verbose_name='Город'),
        ),
    ]
