# Generated by Django 3.0.3 on 2020-02-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20200214_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='yst',
            field=models.URLField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
