# Generated by Django 3.0.3 on 2020-02-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_article_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
