# Generated by Django 3.0.3 on 2020-02-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликован'),
        ),
    ]
