# Generated by Django 3.0.3 on 2020-03-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_auto_20200214_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='down',
            field=models.FileField(null=True, upload_to='static/media/', verbose_name='Документы для закгрузки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='numb',
            field=models.CharField(max_length=150, null=True, verbose_name='Номер лота'),
        ),
    ]
