# Generated by Django 3.0.3 on 2020-03-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0011_auto_20200310_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='down',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Документы для закгрузки'),
        ),
    ]
