# Generated by Django 3.0.3 on 2020-03-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0012_auto_20200310_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='numb',
            field=models.FloatField(null=True, verbose_name='Номер лота'),
        ),
    ]
