# Generated by Django 3.0.3 on 2020-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0013_auto_20200310_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='numb',
            field=models.CharField(max_length=150, null=True, verbose_name='Номер лота'),
        ),
        migrations.AlterField(
            model_name='article',
            name='statzakup',
            field=models.CharField(choices=[('draft', 'Запрос ценовых предложении'), ('win', 'Конкурс'), ('sended', 'Аукцион')], default='draft', max_length=10, verbose_name='Способ закупки'),
        ),
    ]
