# Generated by Django 3.0.3 on 2020-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_auto_20200311_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_open',
            field=models.DateTimeField(null=True, verbose_name='Дата открытия:'),
        ),
    ]
