# Generated by Django 3.0.3 on 2020-03-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200301_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tarif',
        ),
    ]
