# Generated by Django 3.0.3 on 2020-03-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_tarif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
    ]
