# Generated by Django 3.0.3 on 2020-03-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200301_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Price'),
        ),
    ]
