# Generated by Django 3.0.3 on 2020-03-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_tarif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tarif',
        ),
    ]
