# Generated by Django 3.0.3 on 2020-03-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tarif',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Price', verbose_name='Тариф'),
        ),
    ]
