# Generated by Django 3.0.3 on 2020-03-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200301_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='tarif',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.Price', verbose_name='Тариф'),
        ),
    ]
