# Generated by Django 3.0.4 on 2020-03-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200301_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rassylka',
            field=models.BooleanField(default=True),
        ),
    ]
