# Generated by Django 3.0.4 on 2020-03-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_rassylka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
