# Generated by Django 3.0.3 on 2020-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
