# Generated by Django 3.0.3 on 2020-02-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0003_zakazdoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz',
            options={'ordering': ['-id'], 'verbose_name': 'Заявка на участие', 'verbose_name_plural': 'Заявки на участие'},
        ),
        migrations.AlterModelOptions(
            name='zakazdoc',
            options={'ordering': ['-id'], 'verbose_name': 'Запрос документов', 'verbose_name_plural': 'Запросы документов'},
        ),
    ]
