# Generated by Django 3.0.3 on 2020-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0004_auto_20200214_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='status',
            field=models.CharField(choices=[('draft', 'На рассмотрении'), ('win', 'В обработке'), ('send', 'Подача заявки'), ('sended', 'Обработан')], default='draft', max_length=10),
        ),
    ]
