# Generated by Django 3.0.3 on 2020-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0005_auto_20200310_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='zavdate',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения'),
        ),
    ]
